import numpy as np
from trafficSim import *

sim = Simulation()

# Play with these
n = 20
a = -2
b = 12
l = 48

NUM_OF_ROADS = 36
VEHICLE_RATE = 100
STEPS_PER_UPDATE = 10

# Nodes
WEST_RIGHT_START = (-b-l, a)
WEST_LEFT_START = (-b-l, -a)

SOUTH_RIGHT_START = (a, b+l)
SOUTH_LEFT_START = (-a, b+l)

EAST_RIGHT_START = (b+l, -a)
EAST_LEFT_START = (b+l, a)

NORTH_RIGHT_START = (-a, -b-l)
NORTH_LEFT_START = (a, -b-l)

WEST_RIGHT = (-b, a)
WEST_LEFT =	(-b, -a)

SOUTH_RIGHT = (a, b)
SOUTH_LEFT = (-a, b)

EAST_RIGHT = (b, -a)
EAST_LEFT = (b, a)

NORTH_RIGHT = (-a, -b)
NORTH_LEFT = (a, -b)

WEST_RIGHT_START2 = (WEST_RIGHT_START[0], WEST_RIGHT_START[1] - 4)
WEST_LEFT_START2 = (WEST_LEFT_START[0], WEST_LEFT_START[1] + 4)

SOUTH_RIGHT_START2 = (SOUTH_RIGHT_START[0] - 4, SOUTH_RIGHT_START[1])
SOUTH_LEFT_START2 = (SOUTH_LEFT_START[0] + 4, SOUTH_LEFT_START[1])

EAST_RIGHT_START2 = (EAST_RIGHT_START[0], EAST_RIGHT_START[1] + 4)
EAST_LEFT_START2 = (EAST_LEFT_START[0], EAST_LEFT_START[1] - 4)

NORTH_RIGHT_START2 = (NORTH_RIGHT_START[0] + 4, NORTH_RIGHT_START[1])
NORTH_LEFT_START2 = (NORTH_LEFT_START[0] - 4, NORTH_LEFT_START[1])

WEST_RIGHT_START3 = (WEST_RIGHT_START[0], WEST_RIGHT_START[1] - 8)
WEST_LEFT_START3 = (WEST_LEFT_START[0], WEST_LEFT_START[1] + 8)

SOUTH_RIGHT_START3 = (SOUTH_RIGHT_START[0] - 8, SOUTH_RIGHT_START[1])
SOUTH_LEFT_START3 = (SOUTH_LEFT_START[0] + 8, SOUTH_LEFT_START[1])

EAST_RIGHT_START3 = (EAST_RIGHT_START[0], EAST_RIGHT_START[1] + 8)
EAST_LEFT_START3 = (EAST_LEFT_START[0], EAST_LEFT_START[1] - 8)

NORTH_RIGHT_START3 = (NORTH_RIGHT_START[0] + 8, NORTH_RIGHT_START[1])
NORTH_LEFT_START3 = (NORTH_LEFT_START[0] - 8, NORTH_LEFT_START[1])

WEST_RIGHT2 = (WEST_RIGHT[0], WEST_RIGHT[1] - 4)
WEST_LEFT2 =	(WEST_LEFT[0], WEST_LEFT[1] + 4)

SOUTH_RIGHT2 = (SOUTH_RIGHT[0] - 4, SOUTH_RIGHT[1])
SOUTH_LEFT2 = (SOUTH_LEFT[0] + 4, SOUTH_LEFT[1])

EAST_RIGHT2 = (EAST_RIGHT[0], EAST_RIGHT[1] + 4)
EAST_LEFT2 = (EAST_LEFT[0], EAST_LEFT[1] - 4)

NORTH_RIGHT2 = (NORTH_RIGHT[0] + 4, NORTH_RIGHT[1])
NORTH_LEFT2 = (NORTH_LEFT[0] - 4, NORTH_LEFT[1])

WEST_RIGHT3 = (WEST_RIGHT[0], WEST_RIGHT[1] - 8)
WEST_LEFT3 =	(WEST_LEFT[0], WEST_LEFT[1] + 8)

SOUTH_RIGHT3 = (SOUTH_RIGHT[0] - 8, SOUTH_RIGHT[1])
SOUTH_LEFT3 = (SOUTH_LEFT[0] + 8, SOUTH_LEFT[1])

EAST_RIGHT3 = (EAST_RIGHT[0], EAST_RIGHT[1] + 8)
EAST_LEFT3 = (EAST_LEFT[0], EAST_LEFT[1] - 8)

NORTH_RIGHT3 = (NORTH_RIGHT[0] + 8, NORTH_RIGHT[1])
NORTH_LEFT3 = (NORTH_LEFT[0] - 8, NORTH_LEFT[1])

# Roads
WEST_INBOUND = (WEST_RIGHT_START, WEST_RIGHT)
SOUTH_INBOUND = (SOUTH_RIGHT_START, SOUTH_RIGHT)
EAST_INBOUND = (EAST_RIGHT_START, EAST_RIGHT)
NORTH_INBOUND = (NORTH_RIGHT_START, NORTH_RIGHT)

WEST_OUTBOUND = (WEST_LEFT, WEST_LEFT_START)
SOUTH_OUTBOUND = (SOUTH_LEFT, SOUTH_LEFT_START)
EAST_OUTBOUND = (EAST_LEFT, EAST_LEFT_START)
NORTH_OUTBOUND = (NORTH_LEFT, NORTH_LEFT_START)

WEST_STRAIGHT = (WEST_RIGHT, EAST_LEFT)
SOUTH_STRAIGHT = (SOUTH_RIGHT, NORTH_LEFT)
EAST_STRAIGHT = (EAST_RIGHT, WEST_LEFT)
NORTH_STRAIGHT = (NORTH_RIGHT, SOUTH_LEFT)

WEST_RIGHT_TURN = turn_road(WEST_RIGHT, SOUTH_LEFT, TURN_RIGHT, n)
WEST_LEFT_TURN = turn_road(WEST_RIGHT, NORTH_LEFT, TURN_LEFT, n)

SOUTH_RIGHT_TURN = turn_road(SOUTH_RIGHT, EAST_LEFT, TURN_RIGHT, n)
SOUTH_LEFT_TURN = turn_road(SOUTH_RIGHT, WEST_LEFT, TURN_LEFT, n)

EAST_RIGHT_TURN = turn_road(EAST_RIGHT, NORTH_LEFT, TURN_RIGHT, n)
EAST_LEFT_TURN = turn_road(EAST_RIGHT, SOUTH_LEFT, TURN_LEFT, n)

NORTH_RIGHT_TURN = turn_road(NORTH_RIGHT, WEST_LEFT, TURN_RIGHT, n)
NORTH_LEFT_TURN = turn_road(NORTH_RIGHT, EAST_LEFT, TURN_LEFT, n)

WEST_INBOUND2 = (WEST_RIGHT_START2, WEST_RIGHT2)
SOUTH_INBOUND2 = (SOUTH_RIGHT_START2, SOUTH_RIGHT2)
EAST_INBOUND2 = (EAST_RIGHT_START2, EAST_RIGHT2)
NORTH_INBOUND2 = (NORTH_RIGHT_START2, NORTH_RIGHT2)

WEST_OUTBOUND2 = (WEST_LEFT2, WEST_LEFT_START2)
SOUTH_OUTBOUND2 = (SOUTH_LEFT2, SOUTH_LEFT_START2)
EAST_OUTBOUND2 = (EAST_LEFT2, EAST_LEFT_START2)
NORTH_OUTBOUND2 = (NORTH_LEFT2, NORTH_LEFT_START2)

WEST_STRAIGHT2 = (WEST_RIGHT2, EAST_LEFT2)
SOUTH_STRAIGHT2 = (SOUTH_RIGHT2, NORTH_LEFT2)
EAST_STRAIGHT2 = (EAST_RIGHT2, WEST_LEFT2)
NORTH_STRAIGHT2 = (NORTH_RIGHT2, SOUTH_LEFT2)

WEST_RIGHT_TURN2 = turn_road(WEST_RIGHT2, SOUTH_LEFT2, TURN_RIGHT, n)
WEST_LEFT_TURN2 = turn_road(WEST_RIGHT2, NORTH_LEFT2, TURN_LEFT, n)

SOUTH_RIGHT_TURN2 = turn_road(SOUTH_RIGHT2, EAST_LEFT2, TURN_RIGHT, n)
SOUTH_LEFT_TURN2 = turn_road(SOUTH_RIGHT2, WEST_LEFT2, TURN_LEFT, n)

EAST_RIGHT_TURN2 = turn_road(EAST_RIGHT2, NORTH_LEFT2, TURN_RIGHT, n)
EAST_LEFT_TURN2 = turn_road(EAST_RIGHT2, SOUTH_LEFT2, TURN_LEFT, n)

NORTH_RIGHT_TURN2 = turn_road(NORTH_RIGHT2, WEST_LEFT2, TURN_RIGHT, n)
NORTH_LEFT_TURN2 = turn_road(NORTH_RIGHT2, EAST_LEFT2, TURN_LEFT, n)

WEST_INBOUND3 = (WEST_RIGHT_START3, WEST_RIGHT3)
SOUTH_INBOUND3 = (SOUTH_RIGHT_START3, SOUTH_RIGHT3)
EAST_INBOUND3 = (EAST_RIGHT_START3, EAST_RIGHT3)
NORTH_INBOUND3 = (NORTH_RIGHT_START3, NORTH_RIGHT3)

WEST_OUTBOUND3 = (WEST_LEFT3, WEST_LEFT_START3)
SOUTH_OUTBOUND3 = (SOUTH_LEFT3, SOUTH_LEFT_START3)
EAST_OUTBOUND3 = (EAST_LEFT3, EAST_LEFT_START3)
NORTH_OUTBOUND3 = (NORTH_LEFT3, NORTH_LEFT_START3)

WEST_STRAIGHT3 = (WEST_RIGHT3, EAST_LEFT3)
SOUTH_STRAIGHT3 = (SOUTH_RIGHT3, NORTH_LEFT3)
EAST_STRAIGHT3 = (EAST_RIGHT3, WEST_LEFT3)
NORTH_STRAIGHT3 = (NORTH_RIGHT3, SOUTH_LEFT3)

WEST_RIGHT_TURN3 = turn_road(WEST_RIGHT3, SOUTH_LEFT3, TURN_RIGHT, n)
WEST_LEFT_TURN3 = turn_road(WEST_RIGHT3, NORTH_LEFT3, TURN_LEFT, n)

SOUTH_RIGHT_TURN3 = turn_road(SOUTH_RIGHT3, EAST_LEFT3, TURN_RIGHT, n)
SOUTH_LEFT_TURN3 = turn_road(SOUTH_RIGHT3, WEST_LEFT3, TURN_LEFT, n)

EAST_RIGHT_TURN3 = turn_road(EAST_RIGHT3, NORTH_LEFT3, TURN_RIGHT, n)
EAST_LEFT_TURN3 = turn_road(EAST_RIGHT3, SOUTH_LEFT3, TURN_LEFT, n)

NORTH_RIGHT_TURN3 = turn_road(NORTH_RIGHT3, WEST_LEFT3, TURN_RIGHT, n)
NORTH_LEFT_TURN3 = turn_road(NORTH_RIGHT3, EAST_LEFT3, TURN_LEFT, n)

# Trying second intersection to the right of the original one
o2 = (2*b+l, 0)

b_WEST_RIGHT_START = (o2[0] + WEST_RIGHT_START[0], EAST_LEFT[1])
b_WEST_LEFT_START = (o2[0] + WEST_LEFT_START[0], EAST_RIGHT[1])

b_SOUTH_RIGHT_START = (o2[0] + SOUTH_RIGHT_START[0], SOUTH_RIGHT_START[1])
b_SOUTH_LEFT_START = (o2[0] + SOUTH_LEFT_START[0], SOUTH_LEFT_START[1])

b_EAST_RIGHT_START = (o2[0] + EAST_RIGHT_START[0], EAST_RIGHT_START[1])
b_EAST_LEFT_START = (o2[0] + EAST_LEFT_START[0], EAST_LEFT_START[1])

b_NORTH_RIGHT_START = (o2[0] + NORTH_RIGHT_START[0], NORTH_RIGHT_START[1])
b_NORTH_LEFT_START = (o2[0] + NORTH_LEFT_START[0], NORTH_LEFT_START[1])

b_WEST_RIGHT = (o2[0] + WEST_RIGHT[0], EAST_LEFT_START[1])
b_WEST_LEFT = (o2[0] + WEST_LEFT[0], EAST_RIGHT_START[1])

b_SOUTH_RIGHT = (o2[0] + SOUTH_RIGHT[0], SOUTH_RIGHT[1])
b_SOUTH_LEFT = (o2[0] + SOUTH_LEFT[0], SOUTH_LEFT[1])

b_EAST_RIGHT = (o2[0] + EAST_RIGHT[0], EAST_RIGHT[1])
b_EAST_LEFT = (o2[0] + EAST_LEFT[0], EAST_LEFT[1])

b_NORTH_RIGHT = (o2[0] + NORTH_RIGHT[0], NORTH_LEFT[1])
b_NORTH_LEFT = (o2[0] + NORTH_LEFT[0], NORTH_LEFT[1])

b_WEST_RIGHT_START2 = (b_WEST_RIGHT_START[0], b_WEST_RIGHT_START[1] - 4)
b_WEST_LEFT_START2 = (b_WEST_LEFT_START[0], b_WEST_LEFT_START[1] + 4)

b_SOUTH_RIGHT_START2 = (b_SOUTH_RIGHT_START[0] - 4, b_SOUTH_RIGHT_START[1])
b_SOUTH_LEFT_START2 = (b_SOUTH_LEFT_START[0] + 4, b_SOUTH_LEFT_START[1])

b_EAST_RIGHT_START2 = (b_EAST_RIGHT_START[0], b_EAST_RIGHT_START[1] + 4)
b_EAST_LEFT_START2 = (b_EAST_LEFT_START[0], b_EAST_LEFT_START[1] - 4)

b_NORTH_RIGHT_START2 = (b_NORTH_RIGHT_START[0] + 4, b_NORTH_RIGHT_START[1])
b_NORTH_LEFT_START2 = (b_NORTH_LEFT_START[0] - 4, b_NORTH_LEFT_START[1])

b_WEST_RIGHT_START3 = (b_WEST_RIGHT_START[0], b_WEST_RIGHT_START[1] - 8)
b_WEST_LEFT_START3 = (b_WEST_LEFT_START[0], b_WEST_LEFT_START[1] + 8)

b_SOUTH_RIGHT_START3 = (b_SOUTH_RIGHT_START[0] - 8, b_SOUTH_RIGHT_START[1])
b_SOUTH_LEFT_START3 = (b_SOUTH_LEFT_START[0] + 8, b_SOUTH_LEFT_START[1])

b_EAST_RIGHT_START3 = (b_EAST_RIGHT_START[0], b_EAST_RIGHT_START[1] + 8)
b_EAST_LEFT_START3 = (b_EAST_LEFT_START[0], b_EAST_LEFT_START[1] - 8)

b_NORTH_RIGHT_START3 = (b_NORTH_RIGHT_START[0] + 8, b_NORTH_RIGHT_START[1])
b_NORTH_LEFT_START3 = (b_NORTH_LEFT_START[0] - 8, b_NORTH_LEFT_START[1])

b_WEST_RIGHT2 = (b_WEST_RIGHT[0], b_WEST_RIGHT[1] - 4)
b_WEST_LEFT2 =	(b_WEST_LEFT[0], b_WEST_LEFT[1] + 4)

b_SOUTH_RIGHT2 = (b_SOUTH_RIGHT[0] - 4, b_SOUTH_RIGHT[1])
b_SOUTH_LEFT2 = (b_SOUTH_LEFT[0] + 4, b_SOUTH_LEFT[1])

b_EAST_RIGHT2 = (b_EAST_RIGHT[0], b_EAST_RIGHT[1] + 4)
b_EAST_LEFT2 = (b_EAST_LEFT[0], b_EAST_LEFT[1] - 4)

b_NORTH_RIGHT2 = (b_NORTH_RIGHT[0] + 4, b_NORTH_RIGHT[1])
b_NORTH_LEFT2 = (b_NORTH_LEFT[0] - 4, b_NORTH_LEFT[1])

b_WEST_RIGHT3 = (b_WEST_RIGHT[0], b_WEST_RIGHT[1] - 8)
b_WEST_LEFT3 =	(b_WEST_LEFT[0], b_WEST_LEFT[1] + 8)

b_SOUTH_RIGHT3 = (b_SOUTH_RIGHT[0] - 8, b_SOUTH_RIGHT[1])
b_SOUTH_LEFT3 = (b_SOUTH_LEFT[0] + 8, b_SOUTH_LEFT[1])

b_EAST_RIGHT3 = (b_EAST_RIGHT[0], b_EAST_RIGHT[1] + 8)
b_EAST_LEFT3 = (b_EAST_LEFT[0], b_EAST_LEFT[1] - 8)

b_NORTH_RIGHT3 = (b_NORTH_RIGHT[0] + 8, b_NORTH_RIGHT[1])
b_NORTH_LEFT3 = (b_NORTH_LEFT[0] - 8, b_NORTH_LEFT[1])

# Intersection b - Roads
b_WEST_INBOUND = (b_WEST_RIGHT_START, b_WEST_RIGHT)
b_SOUTH_INBOUND = (b_SOUTH_RIGHT_START, b_SOUTH_RIGHT)
b_EAST_INBOUND = (b_EAST_RIGHT_START, b_EAST_RIGHT)
b_NORTH_INBOUND = (b_NORTH_RIGHT_START, b_NORTH_RIGHT)

b_WEST_OUTBOUND = (b_WEST_LEFT, b_WEST_LEFT_START)
b_SOUTH_OUTBOUND = (b_SOUTH_LEFT, b_SOUTH_LEFT_START)
b_EAST_OUTBOUND = (b_EAST_LEFT, b_EAST_LEFT_START)
b_NORTH_OUTBOUND = (b_NORTH_LEFT, b_NORTH_LEFT_START)

b_WEST_STRAIGHT = (b_WEST_RIGHT, b_EAST_LEFT)
b_SOUTH_STRAIGHT = (b_SOUTH_RIGHT, b_NORTH_LEFT)
b_EAST_STRAIGHT = (b_EAST_RIGHT, b_WEST_LEFT)
b_NORTH_STRAIGHT = (b_NORTH_RIGHT, b_SOUTH_LEFT)

b_WEST_RIGHT_TURN = turn_road(b_WEST_RIGHT, b_SOUTH_LEFT, TURN_RIGHT, n)
b_WEST_LEFT_TURN = turn_road(b_WEST_RIGHT, b_NORTH_LEFT, TURN_LEFT, n)

b_SOUTH_RIGHT_TURN = turn_road(b_SOUTH_RIGHT, b_EAST_LEFT, TURN_RIGHT, n)
b_SOUTH_LEFT_TURN = turn_road(b_SOUTH_RIGHT, b_WEST_LEFT, TURN_LEFT, n)

b_EAST_RIGHT_TURN = turn_road(b_EAST_RIGHT, b_NORTH_LEFT, TURN_RIGHT, n)
b_EAST_LEFT_TURN = turn_road(b_EAST_RIGHT, b_SOUTH_LEFT, TURN_LEFT, n)

b_NORTH_RIGHT_TURN = turn_road(b_NORTH_RIGHT, b_WEST_LEFT, TURN_RIGHT, n)
b_NORTH_LEFT_TURN = turn_road(b_NORTH_RIGHT, b_EAST_LEFT, TURN_LEFT, n)

b_WEST_INBOUND2 = (b_WEST_RIGHT_START2, b_WEST_RIGHT2)
b_SOUTH_INBOUND2 = (b_SOUTH_RIGHT_START2, b_SOUTH_RIGHT2)
b_EAST_INBOUND2 = (b_EAST_RIGHT_START2, b_EAST_RIGHT2)
b_NORTH_INBOUND2 = (b_NORTH_RIGHT_START2, b_NORTH_RIGHT2)

b_WEST_OUTBOUND2 = (b_WEST_LEFT2, b_WEST_LEFT_START2)
b_SOUTH_OUTBOUND2 = (b_SOUTH_LEFT2, b_SOUTH_LEFT_START2)
b_EAST_OUTBOUND2 = (b_EAST_LEFT2, b_EAST_LEFT_START2)
b_NORTH_OUTBOUND2 = (b_NORTH_LEFT2, b_NORTH_LEFT_START2)

b_WEST_STRAIGHT2 = (b_WEST_RIGHT2, b_EAST_LEFT2)
b_SOUTH_STRAIGHT2 = (b_SOUTH_RIGHT2, b_NORTH_LEFT2)
b_EAST_STRAIGHT2 = (b_EAST_RIGHT2, b_WEST_LEFT2)
b_NORTH_STRAIGHT2 = (b_NORTH_RIGHT2, b_SOUTH_LEFT2)

b_WEST_RIGHT_TURN2 = turn_road(b_WEST_RIGHT2, b_SOUTH_LEFT2, TURN_RIGHT, n)
b_WEST_LEFT_TURN2 = turn_road(b_WEST_RIGHT2, b_NORTH_LEFT2, TURN_LEFT, n)

b_SOUTH_RIGHT_TURN2 = turn_road(b_SOUTH_RIGHT2, b_EAST_LEFT2, TURN_RIGHT, n)
b_SOUTH_LEFT_TURN2 = turn_road(b_SOUTH_RIGHT2, b_WEST_LEFT2, TURN_LEFT, n)

b_EAST_RIGHT_TURN2 = turn_road(b_EAST_RIGHT2, b_NORTH_LEFT2, TURN_RIGHT, n)
b_EAST_LEFT_TURN2 = turn_road(b_EAST_RIGHT2, b_SOUTH_LEFT2, TURN_LEFT, n)

b_NORTH_RIGHT_TURN2 = turn_road(b_NORTH_RIGHT2, b_WEST_LEFT2, TURN_RIGHT, n)
b_NORTH_LEFT_TURN2 = turn_road(b_NORTH_RIGHT2, b_EAST_LEFT2, TURN_LEFT, n)

b_WEST_INBOUND3 = (b_WEST_RIGHT_START3, b_WEST_RIGHT3)
b_SOUTH_INBOUND3 = (b_SOUTH_RIGHT_START3, b_SOUTH_RIGHT3)
b_EAST_INBOUND3 = (b_EAST_RIGHT_START3, b_EAST_RIGHT3)
b_NORTH_INBOUND3 = (b_NORTH_RIGHT_START3, b_NORTH_RIGHT3)

b_WEST_OUTBOUND3 = (b_WEST_LEFT3, b_WEST_LEFT_START3)
b_SOUTH_OUTBOUND3 = (b_SOUTH_LEFT3, b_SOUTH_LEFT_START3)
b_EAST_OUTBOUND3 = (b_EAST_LEFT3, b_EAST_LEFT_START3)
b_NORTH_OUTBOUND3 = (b_NORTH_LEFT3, b_NORTH_LEFT_START3)

b_WEST_STRAIGHT3 = (b_WEST_RIGHT3, b_EAST_LEFT3)
b_SOUTH_STRAIGHT3 = (b_SOUTH_RIGHT3, b_NORTH_LEFT3)
b_EAST_STRAIGHT3 = (b_EAST_RIGHT3, b_WEST_LEFT3)
b_NORTH_STRAIGHT3 = (b_NORTH_RIGHT3, b_SOUTH_LEFT3)

b_WEST_RIGHT_TURN3 = turn_road(b_WEST_RIGHT3, b_SOUTH_LEFT3, TURN_RIGHT, n)
b_WEST_LEFT_TURN3 = turn_road(b_WEST_RIGHT3, b_NORTH_LEFT3, TURN_LEFT, n)

b_SOUTH_RIGHT_TURN3 = turn_road(b_SOUTH_RIGHT3, b_EAST_LEFT3, TURN_RIGHT, n)
b_SOUTH_LEFT_TURN3 = turn_road(b_SOUTH_RIGHT3, b_WEST_LEFT3, TURN_LEFT, n)

b_EAST_RIGHT_TURN3 = turn_road(b_EAST_RIGHT3, b_NORTH_LEFT3, TURN_RIGHT, n)
b_EAST_LEFT_TURN3 = turn_road(b_EAST_RIGHT3, b_SOUTH_LEFT3, TURN_LEFT, n)

b_NORTH_RIGHT_TURN3 = turn_road(b_NORTH_RIGHT3, b_WEST_LEFT3, TURN_RIGHT, n)
b_NORTH_LEFT_TURN3 = turn_road(b_NORTH_RIGHT3, b_EAST_LEFT3, TURN_LEFT, n)

sim.create_roads([
    WEST_INBOUND,   #0
    SOUTH_INBOUND,  #1
    EAST_INBOUND,   #2
    NORTH_INBOUND,  #3

    WEST_OUTBOUND,  #4
    SOUTH_OUTBOUND, #5
    EAST_OUTBOUND,  #6
    NORTH_OUTBOUND, #7

    WEST_STRAIGHT,  #8
    SOUTH_STRAIGHT, #9
    EAST_STRAIGHT,  #10
    NORTH_STRAIGHT, #11

    WEST_INBOUND2,  #12
    SOUTH_INBOUND2, #13
    EAST_INBOUND2,  #14
    NORTH_INBOUND2, #15

    WEST_OUTBOUND2, #16
    SOUTH_OUTBOUND2, #17
    EAST_OUTBOUND2, #18
    NORTH_OUTBOUND2, #19

    WEST_STRAIGHT2, #20
    SOUTH_STRAIGHT2, #21
    EAST_STRAIGHT2, #22
    NORTH_STRAIGHT2, #23

    WEST_INBOUND3,  #24
    SOUTH_INBOUND3, #25
    EAST_INBOUND3,  #26
    NORTH_INBOUND3, #27

    WEST_OUTBOUND3, #28
    SOUTH_OUTBOUND3, #29
    EAST_OUTBOUND3, #30
    NORTH_OUTBOUND3, #31

    WEST_STRAIGHT3, #32
    SOUTH_STRAIGHT3, #33
    EAST_STRAIGHT3, #34
    NORTH_STRAIGHT3, #35

    *WEST_RIGHT_TURN, #36
    *WEST_LEFT_TURN, #56

    *SOUTH_RIGHT_TURN, #76
    *SOUTH_LEFT_TURN, #96

    *EAST_RIGHT_TURN, #116
    *EAST_LEFT_TURN, #136

    *NORTH_RIGHT_TURN, #156
    *NORTH_LEFT_TURN, #176

    *WEST_RIGHT_TURN2, #196
    *WEST_LEFT_TURN2, #216
    
    *SOUTH_RIGHT_TURN2, #236
    *SOUTH_LEFT_TURN2, #256

    *EAST_RIGHT_TURN2, #276
    *EAST_LEFT_TURN2, #296

    *NORTH_RIGHT_TURN2, #316
    *NORTH_LEFT_TURN2, #336

    *WEST_RIGHT_TURN3, #356
    *WEST_LEFT_TURN3, #376

    *SOUTH_RIGHT_TURN3, #396
    *SOUTH_LEFT_TURN3, #416

    *EAST_RIGHT_TURN3, #436
    *EAST_LEFT_TURN3, #456

    *NORTH_RIGHT_TURN3, #476
    *NORTH_LEFT_TURN3, #496
    
    b_WEST_INBOUND, #516
    b_SOUTH_INBOUND, #517
    b_EAST_INBOUND, #518
    b_NORTH_INBOUND, #519
    
    b_WEST_OUTBOUND, #520
    b_SOUTH_OUTBOUND, #521
    b_EAST_OUTBOUND, #522
    b_NORTH_OUTBOUND, #523
    
    b_WEST_STRAIGHT, #524
    b_SOUTH_STRAIGHT, #525
    b_EAST_STRAIGHT, #526
    b_NORTH_STRAIGHT, #527
    
    b_WEST_INBOUND2, #528
    b_SOUTH_INBOUND2, #529
    b_EAST_INBOUND2, #530
    b_NORTH_INBOUND2, #531
    
    b_WEST_OUTBOUND2, #532
    b_SOUTH_OUTBOUND2, #533
    b_EAST_OUTBOUND2, #534
    b_NORTH_OUTBOUND2, #535
    
    b_WEST_STRAIGHT2, #536
    b_SOUTH_STRAIGHT2, #537
    b_EAST_STRAIGHT2, #538
    b_NORTH_STRAIGHT2, #539
    
    b_WEST_INBOUND3, #540
    b_SOUTH_INBOUND3, #541
    b_EAST_INBOUND3, #542
    b_NORTH_INBOUND3, #543
    
    b_WEST_OUTBOUND3, #544
    b_SOUTH_OUTBOUND3, #545
    b_EAST_OUTBOUND3, #546
    b_NORTH_OUTBOUND3, #547
    
    b_WEST_STRAIGHT3, #548
    b_SOUTH_STRAIGHT3, #549
    b_EAST_STRAIGHT3, #550
    b_NORTH_STRAIGHT3, #551
    
    *b_WEST_RIGHT_TURN, #552
    *b_WEST_LEFT_TURN, #572

    *b_SOUTH_RIGHT_TURN, #592
    *b_SOUTH_LEFT_TURN, #612

    *b_EAST_RIGHT_TURN, #632
    *b_EAST_LEFT_TURN, #652

    *b_NORTH_RIGHT_TURN, #672
    *b_NORTH_LEFT_TURN, #692

    *b_WEST_RIGHT_TURN2, #712
    *b_WEST_LEFT_TURN2, #732
    
    *b_SOUTH_RIGHT_TURN2, #752
    *b_SOUTH_LEFT_TURN2, #772

    *b_EAST_RIGHT_TURN2, #792
    *b_EAST_LEFT_TURN2, #812

    *b_NORTH_RIGHT_TURN2, #832
    *b_NORTH_LEFT_TURN2, #852

    *b_WEST_RIGHT_TURN3, #872
    *b_WEST_LEFT_TURN3, #892

    *b_SOUTH_RIGHT_TURN3, #912
    *b_SOUTH_LEFT_TURN3, #932

    *b_EAST_RIGHT_TURN3, #952
    *b_EAST_LEFT_TURN3, #972

    *b_NORTH_RIGHT_TURN3, #992
    *b_NORTH_LEFT_TURN3, #1012
])

def road(a): return range(a, a+n)

sim.create_gen({
'vehicle_rate': VEHICLE_RATE,
'vehicles':[
    [2, {'path': [0, *road(36), 5]}],
    [1, {'path': [12, 20, 528, 536, 534]}],
    [2, {'path': [24, *road(376), 31]}],
    
    [1, {'path': [1, *road(76), 516, *road(552), 521]}],
    [2, {'path': [13, 21, 19]}],
    [2, {'path': [25, *road(416), 28]}],
    
    [2, {'path': [3, *road(156), 4]}],
    [2, {'path': [15, 23, 17]}],
    [1, {'path': [27, *road(496), 540, *road(892), 547]}],
    
    [1, {'path': [519, *road(672), 2, *road(116), 7]}],
    [2, {'path': [531, *road(539), 533]}],
    [2, {'path': [543, *road(1012), 546]}],
    
    [2, {'path': [518, *road(632), 523]}],
    [1, {'path': [530, 538, 14, 22, 16]}],
    [2, {'path': [542, *road(972), 545]}],
    
    [2, {'path': [517, *road(592), 522]}],
    [2, {'path': [529, 537, 535]}],
    [1, {'path': [541, *road(932), 26, *road(456), 29]}]
]})

sim.create_signal([[0], [1], [2], [3]])
sim.create_signal([[12], [13], [14], [15]])

# Create Green Light for 3rd Lane
sim.create_signal([[24]])
sim.create_signal([[25]])
sim.create_signal([[26]])
sim.create_signal([[27]])

sim.create_signal([[516], [517], [518], [519]])
sim.create_signal([[528], [529], [530], [531]])

sim.create_signal([[540]])
sim.create_signal([[541]])
sim.create_signal([[542]])
sim.create_signal([[543]])
            
# Start simulation
win = Window(sim)
win.zoom = 10
if(sim.isPaused == False):
    win.run(steps_per_update=STEPS_PER_UPDATE)